[package]
name = "pest_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
pest = "2.3.0"
pest_meta = "2.3.0"

[[bin]]
name = "src"
path = "src/main.rs"
